[package]
name = "horas"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
directories = "5.0.1"
toml = "0.8.19"
serde = { version = "1.0.217", features = ["derive"] }
