[[psalms]]
number = 109
tone = "7c"

[[psalms]]
number = 110
tone = "1f"

[[psalms]]
number = 111
tone = "7c"

[[psalms]]
number = 112
tone = "8G"

[[psalms]]
number = 147
tone = "7a"

[magnificat]
tone = "1D"
